### ISSUE TITLE
"known_hosts" file not created

### ISSUE THREAD

**Issue by thorstenkampe** [fioan89/sourcesync#12]
PyCharm 4.0.4 on Windows: *Source Synchronizer* wants to write to `%USERPROFILE%\.ssh\known_hosts` which rarely exists on Windows. *Source Synchronizer* should create the directory and file if it does not exist yet.

**Comment by fioan89** [comment]
This issue should be fixed with  version 1.7. The fix was to create a known_hosts file if it does not exist.
