### ISSUE TITLE
Context menu stopped working after PyCharm 2023.1.1 update

### ISSUE THREAD

**Issue by bastbnl** [fioan89/sourcesync#129]
Just updated to the latest Pycharm community edition version to learn that the source synchronizer plugin simply doesn't work anymore. The context-menu work when I disable the plugin and break (eg: don't appear to show up after an unreasonable amount of time) when I re-enable the plugin

PyCharm 2023.1.1 (Community Edition)
Build #PC-231.8770.66, built on April 27, 2023
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    org.wavescale.sourcesync (2.0.3)

It doesn't really matter where I right click: within an editor or from the project layout. 

The dialog titled "Unloading plugin Source Synchronizer" showing progress does not appear to close within a reasonable amount of time. I'm unable to find anything relevant in the idea logging

**Comment by fioan89** [comment]
Thx for submitting this issue. I've just installed the latest update for IntelliJ and PyCharm - 2023.1.1 First experience: the context menu does pop-up, but only after a couple of seconds. In the previous version (2023.1) there was no issue. If I go to the settings and I switch back to the old UI style  the context menu work seamlessly.

Seems like there are some changes in the new patch regarding the New UI. Can you revert to the old theme style (or downgrade) to 2023.1 until I get a hold on the changes and prepare a new release?

**Comment by fioan89** [comment]
@bastbnl I've release a fix today. Should be approved by Jetbrains in the next two - three days.

**Comment by bastbnl** [comment]
> Can you revert to the old theme style (or downgrade) to 2023.1 until I get a hold on the changes and prepare a new release?
I guess there's no need to this anymore?
