### ISSUE TITLE
Passphrase for SSH keys not supported

### ISSUE THREAD

**Issue by thorstenkampe** [fioan89/sourcesync#14]
Most people use passphrases for SSH keys. This seems not to be supported by *Source Synchronizer* and  makes the new passwordless authentication with keys somehow useless.

**Comment by bastbnl** [comment]
Is a passphrase protected private key supported by this plugin? If not, please add it. It'd add some much value to this plugin

**Comment by fioan89** [comment]
No, currently there is no support for passphrases for SSh keys.

**Comment by DrLuke** [comment]
Please add this. It's sadly unusable in any productive environment with basic security.

**Comment by fioan89** [comment]
I will look into the issues in the next days.

**Comment by fioan89** [comment]
Revision b9b3f24 should fix this issue. The code is not tested yet as I don't have the setup right now. Config structure is now changed so all previous configurations will be lost.

**Comment by fioan89** [comment]
Fixed with 1.9 release.
