### ISSUE TITLE
Target filename different from the source

### ISSUE THREAD

**Issue by Danyhel** [fioan89/sourcesync#166]
Thanks a lot for this plugin, I'm finding it very useful.

I'm just having troubles with single file being synced to target. The issue is with the filename - the target filename is different from the source filename.

I have a folder on the source (Win10) named AAAmenu which is also the project name. And within this folder I have several shell scripts. One of them is aaa_menu.sh.

When I try to sync this single file to the remote server the file is transferred and the content is ok. But the filename changes from aaa_menu.sh to AAAmenu without extension. So it looks like either the folder or project name is being used instead of the original filename.

**Comment by fioan89** [comment]
Thx @Danyhel for the input. I think it's a known issue with SCP configuration when the project folder (AAAmenu in your case) does not exist on the remote destination. Can you confirm:

- that you are using SCP to upload files?
- you are using latest Sourcesync 3.0.2?

**Comment by Danyhel** [comment]
Hi @fioan89, I can confirm both the points as well as the missing folder on the remote server.
I tried to create the folder on the server and now it looks to be working.
Thanks a lot for the advice ;)

**Comment by fioan89** [comment]
Small update @Danyhel the next release (most probably tomorrow) will include a fix for your issue. Sourcesync will determine the correct path on the remote for this corner case, and if the root folder does not exist on the remote then an error is raised with a helpful message.

Also, I want to take the opportunity to say that I also have a [Sourcesync Pro](https://plugins.jetbrains.com/plugin/22318-source-synchronizer-pro?noRedirect=true) version that is able to recursively sync directories, monitor file savings and trigger file sync. On top of that a diff viewer is included, local vs remote. Feedback like missing features, prices or anything that comes to mind is greatly appreciated even if you don't want to upgrade.

**Comment by Danyhel** [comment]
Hi @fioan89! Thanks a lot for the info about the fix, sounds great and will definitely check it. Will also check the Pro version.
