### ISSUE TITLE
Problem opening `~/.ssh/known_hosts` on windows

### ISSUE THREAD

**Issue by leonard84** [fioan89/sourcesync#20]
When trying to connect to a remote host I get this message:

`Could not identify nor create the ssh known hosts file at ~/.ssh/known_hosts. The returned error is:Das System kann den angegebenen Pfad nicht finden` the german text translates to file could not be found.

**Comment by bastbnl** [comment]
Same here, on win10-x64. Does however work properly on win7-x64

**Comment by TakayukiSakai** [comment]
I went through this problem too when connecting to a remote server via sftp.

Apparently, it seems that the path to "known_hosts" file is hard coded and it causes this problem...
https://github.com/fioan89/sourcesync/blob/d480baa089ad989ca18c3b905bf8aa73ff991d37/src/org/wavescale/sourcesync/synchronizer/SFTPFileSynchronizer.java#L30

**Comment by fioan89** [comment]
Thank you I promise I will look into this issues as soon as I can. I can't  commit to a timeline for now, but connection via ssh keys seems to cause a lot of issues lately (mostly because it's not fully featured see https://github.com/fioan89/sourcesync/issues/19 and https://github.com/fioan89/sourcesync/issues/14)

So for the next release the ssh issues are my primary target.

**Comment by fioan89** [comment]
This issue should be fixed with commit d4f922b

**Comment by bastbnl** [comment]
Thanks for the update. Is there something I can do to verify?

**Comment by fioan89** [comment]
You can maybe build the jar and install it. You will have to download the project, open it and create a Intellij Project SDK and assign it to the project.

Then you just need to select Build -> Prepare All Plugin for Deployment. 
I will follow up in the next days with a new release, but it will be great if someone can double check that it works.

**Comment by bastbnl** [comment]
Can I ask you to get me a compiled version? I'll be happy to verify on 7 and 10, both 64 bit

**Comment by fioan89** [comment]
[sourcesync.zip](https://github.com/fioan89/sourcesync/files/248480/sourcesync.zip)

**Comment by bastbnl** [comment]
Thanks! I installed it on Windows 10 and noticed the message was gone. I lost all my sourcesync settings and I remember you mentioned that before. Would be excellent when you would be able to prevent that from happening, but it's not an issue for me. I could understand this being an issue for somebody with multiple connections though

Same on Windows 7.

I haven't checked the passphrase option

Anyway, thanks for your work! I really appreciate it.

**Comment by fioan89** [comment]
Fixed with 1.9 release.
