### ISSUE TITLE
FTP option is not going into the correct root path

### ISSUE THREAD

**Issue by eflowbeach** [fioan89/sourcesync#25]
On my webserver, I have files stored in /public_html/ and when I use that as the 

Root path: /public_html/

it FTP's the files into: /

even if I set Root path to: /public_html/public_html/
the files still end up in: /

**Comment by fioan89** [comment]
I've tested both FTP and FTPS connections with version 1.8 (available in the plugins repository) and it seems to be working fine. My ftp server configures  the chroot_list_enable=YES and chroot_local_user=YES. My test upload's the files into the local user home folder.
 Can you provide the configuration for your ftp server?

**Comment by eflowbeach** [comment]
WIth your latest release it, appears to work now. :-) Thanks!
