### ISSUE TITLE
How can I choose local root folder?

### ISSUE THREAD

**Issue by raevilman** [fioan89/sourcesync#30]
The use case is as follows:
Local structure : src/com/example/tests/
Remote structure : abc/def/com/example/tests

Result of sync : abc/def/src/com/example/tests

How can src folder be ignored?

**Comment by fioan89** [comment]
This is not possible from the plugin itself. The way it works is to take the full path of the file and then subtract the project path. The result is joined with the remote root path.

**Comment by raevilman** [comment]
Oh. Thanks for explaining. 
Should I close this? or you please go ahead and take appropriate action.
