### ISSUE TITLE
The "Add Target" window does not get focus

### ISSUE THREAD

**Issue by trondhindenes** [fioan89/sourcesync#31]
After hitting the "plus" sign, the "Add target" opens in the background, and is impossible to give focuus (on Windows 10). Which leaves me unable to do anything with sourcesync. Please consider giving the "Add Target" a "proper" window.

**Comment by trondhindenes** [comment]
Ok so I figured if I minimize all other windows (including the pycharm main window) before hitting the plus sign I can get to the "Add Target" window. Shouldn't have to do this tho.

**Comment by fioan89** [comment]
This issue should be fixed with commit 7bf6e3a.

**Comment by fioan89** [comment]
Fixed with 1.9 release.
