### ISSUE TITLE
Automatic file synchronization with File Watchers plug-in

### ISSUE THREAD

**Issue by klicperajo** [fioan89/sourcesync#38]
There should be a way to automatically trigger file synchronization whenever a file is saved using the File Watchers plug-in. This can run the .jar binaries whenever a file is changed. But I need help figuring out the right options and what to call. Any comments by the author?

**Comment by fioan89** [comment]
I don't know how File Watches plugin works and how can you call other plugins but here is a starting point for sorucesync: https://github.com/fioan89/sourcesync/blob/master/src/org/wavescale/sourcesync/action/ActionLocalFileToRemote.java

This is where the synchronizers are called and the file sync is started.
