### ISSUE TITLE
Does not work for the new jetbrains Gogland IDE

### ISSUE THREAD

**Issue by akarmarkar** [fioan89/sourcesync#39]
Does not work for the new jetbrains Gogland IDE - I do not see the menu item under tools.

**Comment by akarmarkar** [comment]
After pressing the shortcut key shown in the image, the item appeared under the tools menu.

**Comment by akarmarkar** [comment]
Just realized - the tools menu is taking some seconds to load up on my machine after which the item shows up. Closing the issue.

**Comment by fioan89** [comment]
Is the menu taking that time every-time you try to access it or just the first time?
