### ISSUE TITLE
sftp fails while scp works

### ISSUE THREAD

**Issue by TurBoss** [fioan89/sourcesync#42]
Hi
I'm on linux pycharm 2017.1 and sftp fails to connect while scp works fine

I would like to use sftp due scp limitations

here is the error message I get with sftp:
```
Sync error: Remote dir /home/turboss/app might not exist or you don't have permission on this path!
```

Thanks

**Comment by sirus20x6** [comment]
same here. scp works. sftp does not same error message /home/xxxxxx might not exist....
