### ISSUE TITLE
"On remote we could not change directory into root: \"

### ISSUE THREAD

**Issue by EboMike** [fioan89/sourcesync#61]
With 2.0.0, I can't sync to a remote Linux server using a Windows machine.

I set up my sync via SFTP to a folder like `/var/my/folder`, which is where all the files are.
The IntelliJ project contains all files in a single directory.

When I try to sync, I get this error:

```On remote we could not change directory into root: \```

The backslash makes me think that the Windows backslash isn't converted into a forward slash. Is there anything I can configure to fix this?

**Comment by EboMike** [comment]
I added some debug output to the plugin, and the problem appears to be in SFTPFileSynchronizer.java:

```
        Path remotePath = Paths.get(this.getConnectionInfo().getRootPath()).resolve(uploadLocation);
        [...]
        channelSftp.cd(remotePath.getRoot().toString());
```

On Windows, remotePath will use backslashes, so the path will be something like `\var\my\folder`.  Ultimately, this will cause `remotePath.getRoot().toString()` to return `\`, which fails when SFTP tries to cd into it.

Somebody apparently already sent a PR for this back in 2017 by just hardcoding the root to "/", which may or may not be the right solution here.

The second problem is here:

```
        for (Path current : remotePath) {
            String location = current.toString();
            [...]
            channelSftp.mkdir(location);
            channelSftp.cd(location);
        }
```

This will include actual filename and try to `mkdir` and `cd` into the file.

I could make a PR, but I'm not familiar with the java nio libraries to create a solution that is guaranteed to work in all environments (both client and server). I have a solution locally, but I can't be sure that it won't break some other obscure combination of platforms.

**Comment by fioan89** [comment]
I'll take a look as soon as possible. Weird that it's happening only now... I don't remember touching that part of the code.
