### ISSUE TITLE
Every synced file put in separate directory with same name

### ISSUE THREAD

**Issue by ludmiloff** [fioan89/sourcesync#62]
Well, not much to say here. Just updated the plugin to the latest.

Now every file I sync to server is uploaded into separate directory with the same name.

Anyway, the plugin was a huge timesaving before update.

**Comment by fioan89** [comment]
> into separate directory with the same name.
I'm not sure what do you mean by this. Can you provide an example, screenshot..etc?
Also, what type of remote configuration are you using? What are the local/remote OSs?

**Comment by ludmiloff** [comment]
Hello, thanks for your response.

Here are some screenshots:

**Idea Community Edition, latest version. Part of Project files screen, directory with files in question**
<img width="338" alt="Screenshot 2022-06-02 at 12 56 11" src="https://user-images.githubusercontent.com/673583/171605960-68451ea6-75e7-4b5b-b1fb-d33139deece4.png">

**Desired result at remote server**
<img width="246" alt="Screenshot 2022-06-02 at 12 57 19" src="https://user-images.githubusercontent.com/673583/171606236-cd73b65d-ac30-4560-8551-206d76fe7c5b.png">

**Combined screenshot, showing part of Idea Project files screen and result at remote screen after sync**
<img width="423" alt="Screenshot 2022-06-02 at 12 58 17" src="https://user-images.githubusercontent.com/673583/171606348-d2fdcfbe-fb61-4245-9312-289d1fa80f77.png">

**Same as above, right side showing undesired directory content**
<img width="437" alt="Screenshot 2022-06-02 at 12 58 41" src="https://user-images.githubusercontent.com/673583/171606598-11cbc752-470d-4854-8326-36cf4e34feca.png">

I'm using SFTP connection with SSH key.

**Comment by fioan89** [comment]
> Combined screenshot, showing part of Idea Project files screen and result at remote screen after sync

Is the result from the screenshot done after sync with 1.9 or an older version?

>Same as above, right side showing undesired directory content

Still doesn't help me understand the part about each file being synched in separate directories, each with same name. From the screenshot I can only see one file being synched on remote, but I can't infer anything about the directories in which it/they were synched. Hopefully it doesn't come with a condescending tone, but did you select all 4 files and then "Sync Selectged Files to Remote Target"?

**Comment by ludmiloff** [comment]
> > Combined screenshot, showing part of Idea Project files screen and result at remote screen after sync
> 
> Is the result from the screenshot done after sync with 1.9 or an older version?
> 

No, the second screenshot is after sync with older version. The third is after sync with 2.0

> > Same as above, right side showing undesired directory content
> 
> Still doesn't help me understand the part about each file being synched in separate directories, each with same name. From the screenshot I can only see one file being synched on remote, but I can't infer anything about the directories in which it/they were synched. Hopefully it doesn't come with a condescending tone, but did you select all 4 files and then "Sync Selectged Files to Remote Target"?

Yes, I selected all 4 files and then synced. The problem still exists even if only one file is selected. And what is strange now is that I'm receiving a notification about missing directory or insufficient rights after I moved all files to parent directory (as seen on second screenshot) and tried to sync again.

**Comment by ludmiloff** [comment]
If this can help:

**OLD PLUGIN VERSION**
- directory vfem5

> - file1
> - file2


**NEW PLUGIN VERSION**
- directory vfem5

> - directory named file1

> > - file1

> - directory named file 2

>> - file2

**Comment by fioan89** [comment]
> If this can help:
> 
> **OLD PLUGIN VERSION**
> 
> * directory vfem5
> 
> > * file1
> > * file2
> 
> **NEW PLUGIN VERSION**
> 
> * directory vfem5
> 
> > * directory named file1
> 
> > > * file1
> 
> > * directory named file 2
> 
> > > * file2

Thank you, this is much more helpful. I'll try to investigate as soon as possible. I did not change much in the sync engine with the exception of a few pieces of code used to determine the relative file paths to the root project, and I did this because IntelliJ is planning to remove the support for the calls I've been using.

**Comment by juliant99** [comment]
Hi, I have exactly the the same issue described above. I am also using macOS 12.4 on an M1 processor, and IntelliJ CE.

**Comment by jaemyoun** [comment]
Hi, I have the same issue on IntelliJ CE `Build #IC-221.5921.22, built on June 21, 2022` on macOS 12.4 on Intel i5.

**Comment by beegerous** [comment]
same issue on PyCharm Build #PC-221.5921.27, built on June 22, 2022 on macOs 12.1 on Apple M1

**Comment by EboMike** [comment]
I wonder if this is related to the second issue I mentioned here: https://github.com/fioan89/sourcesync/issues/61#issuecomment-1143199741
Basically, the code goes one directory deeper than it should. In my case, I can't even use sourcesync at all unless I add the getParent() call because my FTP server won't let me create directories like that. I looks like these FTP servers do, which creates the unnecessary directory.

I'm running a custom version of sourcesync with these two changes, and it works fine.

**Comment by EboMike** [comment]
I created https://github.com/fioan89/sourcesync/pull/63 for this. At least on my local setup, I need this to be able to use sourcesync.
