### ISSUE TITLE
Unexpected downgrade from 2.0.1 to 1.9 after updating to pycharm ce 2022.3

### ISSUE THREAD

**Issue by bastbnl** [fioan89/sourcesync#90]
I noticed that the sourcesync plugin was automatically downgraded to version 1.9 after updating to pycharm community edition 2022.3 on my windows 11 machine. The idea log file has this:

```
2022-12-03 08:16:46,157 [    807]   INFO - #c.i.i.p.PluginManager - Ignoring cached broken plugins file from an earlier IDE build (PC-222.4459.20)
2022-12-03 08:16:46,169 [    819]   INFO - #c.i.i.p.PluginManager - Using broken plugins file from IDE distribution
2022-12-03 08:16:47,780 [   2430]   INFO - #c.i.u.i.HttpRequests - Application is not initialized yet; Using default SSL configuration to connect to https://plugins.jetbrains.com/pluginManager/?id=org.wavescale.sourcesync&build=PC-223.7571.203&uuid=04062214530f0b2-6cae-4b3d-9421-ab49a31169b5
2022-12-03 08:16:49,666 [   4316]   INFO - #c.i.i.AppStarter - Downloaded and unpacked compatible version of plugin 'org.wavescale.sourcesync'

```

Version 2.0.1 is not visible in the settings -> plugins dialog. Uninstalling then installing does not show the updated version. The source synchronizer 1.9 dialog is not shown when I click the Source Sync menu item from the Tools menu. Instead an ide error is reported and I can't sync files

I think it has something to do with the editor version:
```
PyCharm 2022.3 (Community Edition)
Build #PC-223.7571.203, built on November 30, 2022
Runtime version: 17.0.5+1-b653.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1978M
Cores: 16
Non-Bundled Plugins:
    org.wavescale.sourcesync (1.9)

```

[gradle.properties ](https://github.com/fioan89/sourcesync/blob/v2.0.1/gradle.properties#L8) has `pluginUntilBuild=222.*`

**Comment by Apollon77** [comment]
Same happens with WebStorm to 2022.3 ...

**Comment by Apollon77** [comment]
PS: hm ... when I see it correctly then I assume that the marketplace version was reset to 1.9 too ...

**Comment by Apollon77** [comment]
I thiunk the reason is 

> Plugin 'Source Synchronizer' (version '2.0.1') is not compatible with the current version of the IDE, because it requires build 222.* or older but the current build is WS-223.7571.168

so it seems that the compatible webstorm version is set "too specific"

**Comment by Apollon77** [comment]
@fioan89 Thank you ... it wopuld be also awesome to get some pointers on https://github.com/fioan89/sourcesync/issues/76 ... I can not use the 2.0.x at all since it was released ... in 1.9 ist was working for me ...

**Comment by fioan89** [comment]
I'll take a look.

**Comment by bastbnl** [comment]
Thanks @fioan89. Quick question: should I be able to install the updated version? pycharm reports that "You already have the latest version of PyCharm and plugins installed"
