### ISSUE TITLE
Pycharm 2202.3 does not support this plugin

### ISSUE THREAD

**Issue by ChineseLincoln** [fioan89/sourcesync#94]
It is a very useful tool, but there is a small problem. The current version of the plug-in does not support 2022.3. Currently, 2022.3 will be downloaded to 1.9 instead of the latest 2. x version due to the plug-in version limitation. Please update it, thank you.

**Comment by ahmednrana** [comment]
As a workaround download the zip from releases. Open it in 7zip and edit the plugin.xml. Change the value 222.* to 224.*. &zip will ask to save it. Save it. Then install the zip in settings-plugins-Install from Local Disk.

**Comment by fioan89** [comment]
Hi all, I've just pushed 2.0.2 with the fix on the marketplace. It should be approved by tomorrow.
